{
 "title": "0- Oracle servers with Statspack",
 "time": { "from": "2018-01-24T05:09:01.473Z", "to": "2022-01-25T05:09:01.473Z" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Database",
    "query": "select distinct foreign_table_schema from information_schema.foreign_tables where foreign_table_name='stats$snapshot'"
   },
   { "name": "new_name", "label": "New server: name" },
   { "name": "new_connection", "label": "New server: connection string", "query": "//host:port/service" },
   { "name": "new_username", "label": "New server: username" },
   { "name": "new_password", "label": "New server: password" }
  ]
 },
 "panels": [
  {
   "title": "oracle_diag()",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "select oracle_diag()" }
   ]
  },
  {
   "title": "Foreign Data Wrapper servers",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select foreign_server_name,oracle_diag(foreign_server_name),*\nfrom information_schema.foreign_tables v\nwhere foreign_table_name='stats$database_instance'"
    }
   ]
  },
  {
   "title": "available servers",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select * from \"oraperfstat$available_servers\"()"
    }
   ]
  },
  {
   "title": "uptime ${server}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "repeat": "server",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select $__time(startup_time),extract(epoch from coalesce(lead(startup_time)over(order by startup_time),localtimestamp)-startup_time)/60/60/24 as uptime\nfrom ${server:doublequote}.stats$database_instance order by 1 desc\n"
    }
   ]
  },
  {
   "title": "uptime ${server}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select $__time(startup_time),extract(epoch from coalesce(lead(startup_time)over(order by startup_time),localtimestamp)-startup_time)/60/60/24 as uptime\nfrom ${server:doublequote}.stats$database_instance order by 1 desc\n"
    }
   ]
  }
 ]
}